| Group | AI Assisted Reporting | Outcome  |
|-------|-----------------------|----------|
| 1     | No                    | Positive |
| 2     | No                    | Negative |
| 3     | Yes                   | Positive |
| 4     | Yes                   | Negative |
| 5     | Yes + GenAI           | Positive |
| 6     | Yes + GenAI           | Negative |

In [23]:
import polars as pl
import pingouin as pg

from pyprojroot import here

root_dir = here()

In [24]:
construct_items = {
    "OA": [
        "OA1",
        "OA2",
        "OA3",
        "OA4",
    ],
    "PA": [
        "PA1",
        "PA2",
        "PA3",
        "PA4",
    ],
    "ITU": [
        "IUT1",
        "IUT2",
        "IUT3",
    ],
    "PRIV": [
        "PRIV1",
        "PRIV2",
        "PRIV3",
    ],
    "RA": [
        "RA1",
        "RA2",
        "RA3",
    ],
    "RC": [
        "RC1",
        "RC2",
        "RC3",
    ],
}

In [25]:
# df_raw = pl.read_excel(
#     root_dir / "data" / "codebook_ntnu_survey_2026-05-14_14-00.xlsx", sheet_name="COMPLETE DATASET"
# )

df_raw = pl.read_csv(root_dir / "data" / "soci" / "cleaned.csv")

In [26]:
required_cols = [
    "ATT_SC",
    "CTRL1",
    "GROUP",
    "IUT1",
    "IUT2",
    "IUT3",
    "MARK1",
    "MARK2",
    "mc1",
    "MC2",
    "OA1",
    "OA2",
    "OA3",
    "OA4",
    "PA1",
    "PA2",
    "PA3",
    "PA4",
    "PAKNOW",
    "PRIV1",
    "PRIV2",
    "PRIV3",
    "RA1",
    "RA2",
    "RA3",
    "RC1",
    "RC2",
    "RC3",
    "RD01_CP",
    "RD02_CP",
    "RD02",
    "RISK",
]

In [27]:
reversed_items = ["PRIV3"]

In [28]:
def correct_reversed(df: pl.DataFrame, reversed_items: list):
    return df.with_columns([(8 - pl.col(c)).alias(c) for c in reversed_items])

In [29]:
df = df_raw.filter(
    pl.col("FT02_01") != "MiriamTest",
).drop_nulls(subset=required_cols).pipe(correct_reversed, reversed_items)

In [30]:
df.select(["TIME_SUM"]).with_row_index().plot.scatter(x="index", y="TIME_SUM")

alt.Chart(...)

In [45]:
df

shape: (250, 70)
┌──────┬────────┬──────┬────────────────┬───┬─────────┬─────────┬─────────┬──────────┐
│ CASE ┆ SERIAL ┆ REF  ┆ QUESTNNR       ┆ … ┆ MAXPAGE ┆ MISSING ┆ MISSREL ┆ TIME_RSI │
│ ---  ┆ ---    ┆ ---  ┆ ---            ┆   ┆ ---     ┆ ---     ┆ ---     ┆ ---      │
│ i64  ┆ str    ┆ str  ┆ str            ┆   ┆ i64     ┆ i64     ┆ i64     ┆ f64      │
╞══════╪════════╪══════╪════════════════╪═══╪═════════╪═════════╪═════════╪══════════╡
│ 193  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 3       ┆ 1       ┆ 1.92     │
│ 195  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 3       ┆ 1       ┆ 1.57     │
│ 196  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 3       ┆ 1       ┆ 1.91     │
│ 197  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 0       ┆ 0       ┆ 2.22     │
│ 198  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 3       ┆ 1       ┆ 1.06     │
│ …    ┆ …      ┆ …    ┆ …              ┆ … ┆ …       ┆ …       ┆ …       ┆ …        │
│ 564  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 3       ┆ 1       ┆ 1.51     │
│ 568  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 0       ┆ 0       ┆ 0.44     │
│ 569  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 3       ┆ 1       ┆ 1.14     │
│ 570  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 0       ┆ 0       ┆ 0.71     │
│ 572  ┆ null   ┆ null ┆ affective_grid ┆ … ┆ 22      ┆ 3       ┆ 1       ┆ 0.44     │
└──────┴────────┴──────┴────────────────┴───┴─────────┴─────────┴─────────┴──────────┘

In [31]:
# check if ctl was answered correctly
assert df["CTRL1"].unique().item() == 2

In [32]:
# check if comprehension check was answered correctly
assert df["ATT_SC"].unique().item() == 1

In [33]:
df["GROUP"].value_counts().sort(by="GROUP").plot.bar(
    x="GROUP",
    y="count",
)

alt.Chart(...)

## Cronbachs Alpha

In [34]:
ca_threshold = 0.7


for construct, items in construct_items.items():
    ca = pg.cronbach_alpha(df[items].to_pandas())[0]
    if ca < ca_threshold:
        print(f"Cr. alpha too low for {construct}: {round(ca, 3)}")
    else:
        print(f"Cr. alpha fine low for {construct}: {round(ca, 3)}")

Cr. alpha too low for OA: 0.511
Cr. alpha too low for PA: 0.621
Cr. alpha fine low for ITU: 0.967
Cr. alpha too low for PRIV: 0.578
Cr. alpha fine low for RA: 0.794
Cr. alpha too low for RC: 0.646

In [35]:
construct_items

{'OA': ['OA1', 'OA2', 'OA3', 'OA4'],
 'PA': ['PA1', 'PA2', 'PA3', 'PA4'],
 'ITU': ['IUT1', 'IUT2', 'IUT3'],
 'PRIV': ['PRIV1', 'PRIV2', 'PRIV3'],
 'RA': ['RA1', 'RA2', 'RA3'],
 'RC': ['RC1', 'RC2', 'RC3']}

In [36]:
df[construct_items["PRIV"]].corr()

shape: (3, 3)
┌──────────┬──────────┬──────────┐
│ PRIV1    ┆ PRIV2    ┆ PRIV3    │
│ ---      ┆ ---      ┆ ---      │
│ f64      ┆ f64      ┆ f64      │
╞══════════╪══════════╪══════════╡
│ 1.0      ┆ 0.561509 ┆ 0.233376 │
│ 0.561509 ┆ 1.0      ┆ 0.229927 │
│ 0.233376 ┆ 0.229927 ┆ 1.0      │
└──────────┴──────────┴──────────┘

## Manipulation Check

In [37]:
df.group_by("GROUP").agg(pl.col("mc1").std()).sort(by="GROUP")

shape: (6, 2)
┌───────┬──────────┐
│ GROUP ┆ mc1      │
│ ---   ┆ ---      │
│ i64   ┆ f64      │
╞═══════╪══════════╡
│ 1     ┆ 0.9337   │
│ 2     ┆ 1.423114 │
│ 3     ┆ 1.226901 │
│ 4     ┆ 1.151189 │
│ 5     ┆ 1.292554 │
│ 6     ┆ 0.806947 │
└───────┴──────────┘

In [48]:
df.group_by("GROUP").agg(pl.col("mc1").mean()).sort(by="GROUP").plot.bar(
    x="GROUP", y="mc1"
)

alt.Chart(...)

In [46]:
df.group_by("GROUP").agg(pl.col("MC2").mean()).sort(by="GROUP").plot.bar(
    x="GROUP", y="MC2"
)

alt.Chart(...)

In [40]:
from scipy.stats import mannwhitneyu

In [44]:
# _, p = mannwhitneyu(males, females)